//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkin
    {
        public int BookingId { get; set; }
        public string GuestName { get; set; }
        public int contact { get; set; }
        public string address { get; set; }
        public int quantity { get; set; }
        public System.DateTime dt { get; set; }
        public int Total_days { get; set; }
        public double bill { get; set; }
    }
}
