//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int Id { get; set; }
        public string GusestName { get; set; }
        public long Contact { get; set; }
        public string Address { get; set; }
        public string Roomtype { get; set; }
        public int Quantity { get; set; }
        public int Staydays { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    }
}
