//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetail
    {
        public int R_Id { get; set; }
        public string RoomType { get; set; }
        public double Price { get; set; }
        public int NumRoomsPR { get; set; }
        public int NumRoomsDE { get; set; }
        public int NumRoomsST { get; set; }
    }
}
